### ISSUE TITLE
Doku - improvements

### ISSUE THREAD

**Issue by FelixMau** [sedos-project/organization#10]
While trying to upload several Datasets via the API on the [SEDOS Project](https://sedos-project.github.io/.github/data_requirements/overview/) I faced some issues that possibly could be fixed by a improved dokumentation/description and examples: 

#### Metadata
- [x] It should be mentioned how Name and Shema and what they do (Giving the Name to the Metadata on the OEP and defining where it is saved) 
- [x] List available data types and how they should be formatted in the csv
- [x] Harmonize datatype names in examples and doku (sometimes integers are called int and text is called string... ) Maybe a larger set of accepted data types would also be a handy solution?
- [x] Metadata must contain `"@context"` to register on Databus and be SPARQL-able contain:
`"@context": "https://raw.githubusercontent.com/OpenEnergyPlatform/oemetadata/master/metadata/latest/context.json"`

#### CSV files:
- [x] Formatting information for data types with an example maybe: 

| dtype      | csv formatting example    | comment | 
|--------------|-----------|------------|
| json | "{""key1"": ""text"", ""key2"": ""text""}"      | csv seperator should not be "," , keys as text, what happens to floats?  |
| float array     | [float, float]  | arrays with strings should be formatted as strings ("['string1', 'string2']" |
| text     |"text"  | String data should have text as datatype |
| integer     |integer  | int data should have integer as datatype |

#### Databus:
- [x] Create user on[databus](https://energy.databus.dbpedia.org/) (what are they?)
- [x] Generate API-key on Profile->settings  at bottom of page
- [x] "Databus Account Name" reffers to profile name on Databus (not e-mail adress)

**Comment by chrwm** [comment]
Thanks for collecting the documation improvements. Maybe start a new branch from `develop`, e.g. `feature-10-improve-docs` and push your commits there. Then someone can review your changes once you finished implementation.
