### ISSUE TITLE
Add permalink:true to documentation

### ISSUE THREAD

**Issue by srhbrnds** [sedos-project/organization#7]
Has anyone deleted permalink:true in the mkdocs.yml for a reason, or did it just happen by accident? I like this feature to link to subheadings. If you agree, i would add it again! @chrwm @henhuy

**Comment by chrwm** [comment]
It could have been an accident. From my side, please add it again.

**Comment by srhbrnds** [comment]
I included it in the PR https://github.com/sedos-project/organization/pull/4.
